name: Send Text Message Scheduled

on:
  schedule:
    - cron:  '0 * * * *'
jobs:
  data_refresh:
    name: send a message
    env:
      TWILIO_SID: ${{ secrets.TWILIO_SID }}
      TWILIO_TOKEN: ${{ secrets.TWILIO_TOKEN }}
      TWILIO_PHONE_NUMBER: ${{ secrets.TWILIO_PHONE_NUMBER }}
      PHONE_NUMBER_RP: ${{ secrets.PHONE_NUMBER_RP }}
      PHONE_NUMBER_GM: ${{ secrets.PHONE_NUMBER_GM }}
    runs-on: ubuntu-latest
    container:
     image: docker.io/richpauloo/tdox:prod.0.0.01
    steps:
      - name: (1) Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: 'main'
      - name: (2) Message and iterate counter
        run: |
          source('R/message.R')
        shell: Rscript {0} 
      - name: (3) GitHub Action for committing changes to a repository
        uses: devops-infra/action-commit-push@v0.9.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_prefix: "[AUTO-COMMIT] iterate counter"
      - name: (4) Session info
        run: |
          sessionInfo()
        shell: Rscript {0}
